language: go
install:
  - go get github.com/suveng/ink
  - ink build

script:
  - cd ./blog/public/
  - git init
  - git config user.name "swyroc"
  - git config user.email "1182060139@qq.com"
  - git add .
  - git commit -m "update blogs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branch:
  only:
    -source
env:
  global:
    - GH_REF: github.com/swyroc/blog
